apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crud-ingress
spec:
  rules:
  - host: "crud-prod.apps.dmi3lab.online"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: crud-app
            port:
              number: 8080
  tls:
  - hosts:
    - crud-prod.apps.dmi3lab.online
    secretName: crud-app-cert
