apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crud-app-cert
spec:
  secretName: crud-app-cert
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: clusterissuer
  dnsNames:
  - "crud-prod.apps.dmi3lab.online"
