apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: prod
  sre-team: red


patchesStrategicMerge:
- crud-app-replicas.yaml
- crud-ingress.yaml

imageTags:
  - name: dmi3mis/crud-app
    newTag: 1ceeaca387e98f5ba0a87e6e432f9f65a25c5ce2

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: mysql
  type: Opaque
  behavior: replace
  literals:
  - database=crud
  - user=produser
  - password=prodpass
  - root-password=produserpass
  - server=mysql
labels:
- includeSelectors: true
  pairs:
    environment: prod
    sre-team: red
