apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - crud-apps-prod-certificate.yaml

commonLabels:
  environment: prod
  sre-team: red


patchesStrategicMerge:
- crud-app-replicas.yaml
- crud-ingress.yaml

imageTags:
  - name: dmi3mis/crud-app
    newTag: da440803e318b3ad3ddf369189b560a776eca2a1

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: mysql
  type: Opaque
  behavior: replace
  literals:
  - database=crud
  - user=produser
  - password=prodpass
  - root-password=produserpass
  - server=mysql
labels:
- includeSelectors: true
  pairs:
    environment: prod
    sre-team: red