apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mysql-deploy.yaml
- mysql-service.yaml
- crud-service.yaml
- crud-app-deploy.yaml
- crud-ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- literals:
  - database=crud
  - user=user
  - password=pass
  - root-password=rootpass
  - server=mysql
  name: mysql
  type: Opaque
