apiVersion: v1
kind: Secret
metadata:
    name: mysql
    annotations:
        kustomize.config.k8s.io/needs-hash: "false"
        kustomize.config.k8s.io/behavior: replace
stringData:
  database: crud
  user: user
  password: pass
  root-password: rootpass
  server: mysql
